### ISSUE TITLE
Invalid hexlify issue

### ISSUE THREAD

**Issue by Shebofd** [lmusarella/Pancakeswap-Prediction-Bot-2023#26]
Hello, 

I have an issue when I try to start the bot up, I believe it has to do with the way Metamask exports the private key, does anyone have the same issue or do I need to configure something else differently? see below:

`/Users/sanderwesterbeek/Pancakeswap-Prediction-Bot-2023/node_modules/@ethersproject/logger/lib/index.js:247
        throw this.makeError(message, code, params);
        ^

Error: invalid hexlify value (argument="value", value="", code=INVALID_ARGUMENT, version=bytes/5.7.0)
    at Logger.makeError (/Users/Pancakeswap-Prediction-Bot-2023/node_modules/@ethersproject/logger/lib/index.js:238:21)
    at Logger.throwError (/Users/Pancakeswap-Prediction-Bot-2023/node_modules/@ethersproject/logger/lib/index.js:247:20)
    at Logger.throwArgumentError (/Users/Pancakeswap-Prediction-Bot-2023/node_modules/@ethersproject/logger/lib/index.js:250:21)
    at hexlify (/Users/Pancakeswap-Prediction-Bot-2023/node_modules/@ethersproject/bytes/lib/index.js:200:19)
    at new SigningKey (/Users/Pancakeswap-Prediction-Bot-2023/node_modules/@ethersproject/signing-key/lib/index.js:20:82)
    at new Wallet (/Users/Pancakeswap-Prediction-Bot-2023/node_modules/@ethersproject/wallet/lib/index.js:120:36)
    at Object.<anonymous> (/Users/Pancakeswap-Prediction-Bot-2023/bot-lib/wallet/wallet.module.js:29:16)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32) {
  reason: 'invalid hexlify value',
  code: 'INVALID_ARGUMENT',
  argument: 'value',
  value: ''
`

**Comment by lmusarella** [comment]
I managed to replicate your error, most likely it is the length of your private key which does not correspond to 64 alphanumeric characters. 

Maybe this can help you:
- https://stackoverflow.com/questions/76052632/how-to-fix-invalid-hexlify-value-error-in-ethers-js
- https://github.com/ethers-io/ethers.js/issues/1166

**Comment by Shebofd** [comment]
I tried both options, doesn't seem to work.

I read online that it could be because of Metamask not prefixing keys with '0x'

Otherwise, could I have made a mistake in typing it in the .env file?

PERSONAL_WALLET_PRIVATE_KEY = 000000000000000000000
PERSONAL_WALLET_ADDRESS = 00000000000000000000

It should be written like the above, right?

Thanks

**Comment by lmusarella** [comment]
PERSONAL_WALLET_PRIVATE_KEY = 6t81bef21644c54c2bc82d80086d85ba099b9eb1d42546dd324abf49e7599bf9 # Private KEY
PERSONAL_WALLET_ADDRESS = '0x0T40e4F3606aE2F41DAc9bB67606f41212345678' # Address personal Wallet

I have something like this.

**Comment by Shebofd** [comment]
unfortunately not yet. I will let you know if I have a solution. Thanks for the help so far! :)

**Comment by Shebofd** [comment]
See below, someone else who encountered a similar issue. my error also gives: value='' could it be the same? maybe 0x or 0x00 need to be before wallet/private key address?


It's a bit strange that answers about ETH are so few.

I met the same problem. for your case, running :

t = await i.safeTransferFrom(accounts[1], accounts[9], 0, "6666666666666666666", "", {from: accounts[1]})
will get this error:

Error: invalid arrayify value (argument="value", value="", code=INVALID_ARGUMENT, version=bytes/5.0.5)
    at evalmachine.<anonymous>:1:11
notice the error backtrace value="", means here you got the problem

convert "" to 0x or 0x00 will work, because in your function, you declared a parameter with type bytes, which "seems" only accept parameter starting with 0x.
